name: Racket Test

on:
  push:
    branches:
      - "*"
    paths:
      - "**test.yml"
      - "**.rkt"
      - "**.scrbl"
  pull_request:
    branches:
      - "*"
    paths:
      - "**.rkt"
      - "**.scrbl"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-variant: ["BC", "CS"]
        racket-version: ["stable", "current"]
    steps:
      - uses: actions/checkout@master
      - name: Cache installed packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/racket
            ~/.local/share/racket
          key: ${{ runner.os }}-primes
      - name: Setup Racket
        uses: Bogdanp/setup-racket@v1.7
        with:
          architecture: "x64" # (x64 or x86), ignored on Linux
          distribution: "minimal"
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - run: raco pkg install --auto --skip-installed
      - run: |
          raco test .
