name: Racket Coverage

on:
  push:
    branches:
      - "*"
    paths:
      - "**coverage.yml"
      - "**.rkt"
      - "**.scrbl"
  pull_request:
    branches:
      - "*"
    paths:
      - "**.rkt"
      - "**.scrbl"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    environment: test-env
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    steps:
      - uses: actions/checkout@master
      - name: Cache installed packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/racket
            ~/.local/share/racket
          key: ${{ runner.os }}-primes
      - name: Setup Racket
        uses: Bogdanp/setup-racket@v1.7
        with:
          architecture: "x64"
          distribution: "minimal"
          variant: "CS"
          version: "current"
          packages: "cover, cover-coveralls"
      - run: raco pkg install --auto --skip-installed
      - run: |
          raco test .
          raco cover -b -f coveralls .
